### ISSUE TITLE
Filter singleton k-mers

### ISSUE THREAD

**Issue by aldro61** [aldro61/kover#23]
Filtering k-mers that are only present in one genome could greatly improve the running time and shouldn't affect the accuracy of the models.

**Comment by aldro61** [comment]
I made a small test with a C. difficile dataset. There are 32752570 k-mers in total. Here is the distribution of the number of occurrences!

![kmercounts](https://cloud.githubusercontent.com/assets/2374980/15340917/f25b87a4-1c59-11e6-9157-16badfa017e6.png)

There are a few millions k-mers that are only in one genome.

**Comment by aldro61** [comment]
This is implemented when the kover dataset is created from contigs (fasta), but not from a surveyor TSV matrix.

**Comment by saranpons3** [comment]
Hello, 
         I would like to know that what is the significant of K-mers which are occurring only once in the reads data set?

**Comment by aldro61** [comment]
Hi! When your dataset consists of multiple genomes, a k-mer that occurs in only one genome is very unlikely to be a good predictor of the phenotype. K-mers that are present/absent in larger groups of genomes are better predictors.

**Comment by saranpons3** [comment]
Hi aldro61, I have reads data set of a single organism. I would like to know that what is the significance of kmers which are occurring only once in the entire data set. I'm developing a Kmer counter tool. I want to know that Is it must for a Kmer counter tool to generate kmers which are occurring only once and write to the final output file?

**Comment by aldro61** [comment]
You cannot use Kover with a single organisms. You need to have many genomes. I am not very familiar with k-mer counting tools. We use the [DSK](https://github.com/GATB/dsk) k-mer counter. However, I suspect that a k-mer occurring only once in a set of reads would likely be a sequencing error and would not be important. Does this answer your question?

**Comment by saranpons3** [comment]
Hello aldro61, I understand your answer. In Biostars forum, someone said kmers occurring only once could be significant post assembly (https://www.biostars.org/p/266532/#266583). Is this correct?

Also, I would like to know that what would be the length of kmer for the lengthier reads which are generated by 3rd generation sequencing technology such as Nanopore and Pacbio machines.

**Comment by aldro61** [comment]
I believe they could be important depending on your application. For machine learning (including Kover), they shouldn't be. 

For the k-met length, you will find guidelines for selecting it in our paper (see the Kover readme file). Briefly, it is an application specific parameter and must be chosen based on domain knowledge or else, many values must be tried and scores with respect to your objective. In Kover, you would use the accuracy of the predictions to score a k-mer length. 

If this does not clarify things, I think it would be best to ask this question on a forum, such as Biostars. You will find people that are a lot more knowledgeable than me about k-mer counting. 

Best,
Alexandre

**Comment by saranpons3** [comment]
Ok. Thanks for your time and answering my question.
