### ISSUE TITLE
K-mer matrix input format requires same number of characters

### ISSUE THREAD

**Issue by goepp** [aldro61/kover#52]
Hi,
When using the `kover dataset create from-tsv` command with the following tsv file as the genomic data argument:
![design](https://user-images.githubusercontent.com/28815615/75254089-b9804d80-57d7-11ea-9828-36d1593733d6.png)
I get the error:
![error](https://user-images.githubusercontent.com/28815615/75254387-36132c00-57d8-11ea-9560-d35e1d0371a2.png)
This issue disappears if the first column of the tsv file has the same number of character across all lines, like this (note the three last lines of the first column):
![design_good](https://user-images.githubusercontent.com/28815615/75255865-87241f80-57da-11ea-8725-0c291b085f19.png)
I believe this is due to the function `get_kmer_count` in `create.py`. 
More precisely, an error is thrown after `if content_size % line_size != 0:` on line 135, which seems to implicitely assume that all kmer IDs have the same number of character.

**Comment by aldro61** [comment]
Hi @goepp! Yes indeed we assume that all kmer ids are of the same length. This allows to rapidly count the number of lines in huge files without having to read through them. The speed benefits of this is very big when considering millions of kmers.

To fix this, you can simply use padding in the kmer ids.

**Comment by goepp** [comment]
Got it, thanks. Maybe adding it to the "K-mer matrix" section of the [documentation](https://aldro61.github.io/kover/doc_input_formats.html#k-mer-matrix) could be useful?

**Comment by aldro61** [comment]
Absolutely, I’m surprised it’s not there yet. I will add it. Sorry for the confusion. 

Cheers,
Alex
