### ISSUE TITLE
Question: Does Kover work well for inter-species comparisons?

### ISSUE THREAD

**Issue by j-kominek** [aldro61/kover#58]
Hi, I posted this question on Biostars (https://www.biostars.org/p/451785/) but it shows that it's been months since you've been there, so I thought I'd ask here, if you don't mind:

I intend to run a relatively large-scale genotype-to-phenotype assessment (hundreds of genomes. dozens of phenotypes) and would like to use kover to provide targets for the bases of the phenotypes. My problem is that the dataset covers different species, rather than strains of the same species, so the sequences are much divergent, and so I don't think that running kover the 'default' way would work too well. To overcome that, I was thinking about using the amino acid sequences of proteins identified in each species, but I am not sure if kover would accept that as a valid input to the '--from-contigs' option? Alternatively, would it work fine if I passed the k-mer matrix for amino-acid sequences to '--from-tsv', rather than nucleotides? Thanks in advance for all your help!
-Jacek K.

**Comment by aldro61** [comment]
Hi Jacek,

The `--from-contigs` option won't work for amino-acid sequences. In that case, I would recommend precomputing the k-mer matrix and creating the dataset with `--from-tsv`. The entries of this matrix can really represent the presence/absence of anything, e.g., amino-acid sequences, point mutations, etc. The only thing to watch out for is that the feature identifiers must have the same length (what is under the "kmers" column here http://aldro61.github.io/kover/doc_input_formats.html).

I hope that this helps!
Alex

**Comment by aldro61** [comment]
Will copy my answer to Biostars in case it can help someone else. Thanks for the question!

**Comment by aldro61** [comment]
@j-kominek if this solves your issue, could you please upvote it on biostars? Thanks!

**Comment by j-kominek** [comment]
Hi Alex, sorry it took me awhile to get back to it, but yes, I upvoted your answer and marked the issue as solved.
