### ISSUE TITLE
Errors reporting "tp" in both report.txt and  results.json

### ISSUE THREAD

**Issue by augustkx** [aldro61/kover#64]
Hi, 
Errors reporting "tp" in both report.txt and  results.json.
When there are 3 tp in my dataset, it reported 0.  All of the 3 samples were wrongly predicted to 0, and were correctly reported as "fn". I  double-checked from the samples reported by "test_errors" in  results.json, there are 3 "tp". 

Besides, results.json reported "fn": [3],  which if is correct,  then there must be at least 3 tp in logical reasoning
.

Could you please let me know if "classifications" in results.json surely be correct or not? I will appreciate it, as I am rushing to get results, I can calculate scores from "classifications" if they are correct. Thanks!

**Comment by aldro61** [comment]
Hi @augustkx,

This behaviour seems normal. 

TP is the number of examples with a positive label that were correctly predicted as positive (see https://en.m.wikipedia.org/wiki/Confusion_matrix). 

If there are 3 positive examples in your dataset and they are all incorrectly predicted, then there are 3 false negatives and no true positives. 

I hope this helps,
Alex

**Comment by aldro61** [comment]
I will close since this does not appear to be an issue. Please do not hesitate to reopen if I misunderstood or if it is still unclear.

**Comment by augustkx** [comment]
Hi Alex, 
Ah, sorry for the mistake from my side. Thank you very much for the explanation.
