### ISSUE TITLE
Unable to create a working dataset 

### ISSUE THREAD

**Issue by Jasmeer57** [aldro61/kover#69]
After going the through the documentation, I evaluated that there can be two methods of giving an input data into Kover, i.e. KmerMatrix, Reads and Contigs. I have Whole Genome Sequences of Acinetobacter baumannii in FASTA format. I successfully installed Kover into my system and it worked on the sample dataset, for testing it to work on my dataset I made a genomic dataset in the contig input format, where I gave the PATH and Genome ID and stored the FASTA file in a new folder. I also created a metadata file for the same but an error occurred that says "Traceback". Please help me resolve this issue. Hoping for a positive reply!

Thanks!

![image](https://user-images.githubusercontent.com/62324066/177978531-d506d23b-e2b5-4e9d-91e2-d4eed1bae5a9.png)
![image](https://user-images.githubusercontent.com/62324066/177978541-eb41a2a7-eedb-497f-b751-92e179804402.png)
![image](https://user-images.githubusercontent.com/62324066/177978549-4fe6e796-1946-44d3-abcc-96264270a7e3.png)

My data
![image](https://user-images.githubusercontent.com/62324066/177978688-30cba4a9-8f9f-4bc2-98b9-925e7b5b499d.png)
![image](https://user-images.githubusercontent.com/62324066/177978723-a559037e-076d-4323-8d8c-ea782f78387e.png)
![image](https://user-images.githubusercontent.com/62324066/177978779-f97ca0cd-cbb0-4b93-ba9e-2e1a8cd1f475.png)
![image](https://user-images.githubusercontent.com/62324066/177978804-c20f7080-4d57-48e4-ba13-aa0b8bee88a2.png)

**Comment by aldro61** [comment]
Hi @Jasmeer57! I see two possibilities here:

1. The installer failed to compile the k-mer counting tools, which are coded in C++. Please make sure that all the depencies are installed ([see here](https://aldro61.github.io/kover/doc_installation.html)). If they are, please run the installer and share the output that is printed in the terminal with me.

2. In the file for the `--genomic-data` argument to `kover dataset create from-contigs`, you should specify the full path to the fasta file for each genome. I see that you currently just specify the directory. I would try fixing that first.

Cheers,
Alex

**Comment by Jasmeer57** [comment]
Hello Alex,

I have gone through both the points and ensured that I have all the dependencies installed. Also, I have changed the genomic data file to full path than just the directory. Screenshots for the same are attached below. It'll be very kind of you to help me fix this issue. 

![image](https://user-images.githubusercontent.com/62324066/178472997-07c9bca5-6be1-4bb1-be1f-dcf15625df38.png)
![image](https://user-images.githubusercontent.com/62324066/178473030-5b79d950-04bb-432c-8277-ccde5b779932.png)
